/**
 * Applies functions over value from left to right.
 * @param value - The initial value to pipe
 * @param fns - The functions to pipe the value through
 * @returns The final value after all functions have been applied
 */
export function pipe<A>(value: A): A;
export function pipe<A, B>(value: A, a: (input: A) => B): B;
export function pipe<A, B, C>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
): C;
export function pipe<A, B, C, D>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
): D;
export function pipe<A, B, C, D, E>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
): E;
export function pipe<A, B, C, D, E, F>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
): F;
export function pipe<A, B, C, D, E, F, G>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
): G;
export function pipe<A, B, C, D, E, F, G, H>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
): H;
export function pipe<A, B, C, D, E, F, G, H, I>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
): I;
export function pipe<A, B, C, D, E, F, G, H, I, J>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
): J;
export function pipe<A, B, C, D, E, F, G, H, I, J, K>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
): K;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
): L;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
): M;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
): N;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
): O;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
): P;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
  p: (input: P) => Q,
): Q;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
  p: (input: P) => Q,
  q: (input: Q) => R,
): R;
export function pipe<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
  p: (input: P) => Q,
  q: (input: Q) => R,
  r: (input: R) => S,
): S;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
  p: (input: P) => Q,
  q: (input: Q) => R,
  r: (input: R) => S,
  s: (input: S) => T,
): T;
export function pipe<
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
>(
  value: A,
  a: (input: A) => B,
  b: (input: B) => C,
  c: (input: C) => D,
  d: (input: D) => E,
  e: (input: E) => F,
  f: (input: F) => G,
  g: (input: G) => H,
  h: (input: H) => I,
  i: (input: I) => J,
  j: (input: J) => K,
  k: (input: K) => L,
  l: (input: L) => M,
  m: (input: M) => N,
  n: (input: N) => O,
  o: (input: O) => P,
  p: (input: P) => Q,
  q: (input: Q) => R,
  r: (input: R) => S,
  s: (input: S) => T,
  t: (input: T) => U,
): U;
export function pipe(
  value: unknown,
  ...fns: Array<(input: unknown) => unknown>
): unknown {
  for (const fn of fns) {
    value = fn(value);
  }
  return value;
}
